{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "/home/cs/Documents/maddpg/experiments",
    "dependencies": [
      "munch==2.3.2",
      "numpy==1.15.4",
      "pymongo==3.7.2",
      "PyYAML==3.13",
      "sacred==0.7.4",
      "tensorflow==1.12.0"
    ],
    "mainfile": "train.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "train.py",
        "_sources/train_557b99bd766b45d1671290338655249b.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/home/cs/Documents/venvs/pymarl-cqmix/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 46, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"/home/cs/Documents/maddpg/experiments/train.py\", line 276, in my_main\n    train(arglist, logger)\n",
    "  File \"/home/cs/Documents/maddpg/experiments/train.py\", line 113, in train\n    U.load_state(arglist.load_dir)\n",
    "  File \"/home/cs/Documents/maddpg/maddpg/common/tf_util.py\", line 233, in load_state\n    saver.restore(get_session(), fname)\n",
    "  File \"/home/cs/Documents/venvs/pymarl-cqmix/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1536, in restore\n    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):\n",
    "  File \"/home/cs/Documents/venvs/pymarl-cqmix/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py\", line 364, in checkpoint_exists\n    if file_io.get_matching_files(pathname):\n",
    "  File \"/home/cs/Documents/venvs/pymarl-cqmix/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py\", line 342, in get_matching_files\n    for single_filename in filename\n",
    "  File \"/home/cs/Documents/venvs/pymarl-cqmix/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py\", line 528, in __exit__\n    c_api.TF_GetCode(self.status.status))\n",
    "tensorflow.python.framework.errors_impl.NotFoundError: /tmp/policy; No such file or directory\n"
  ],
  "heartbeat": "2019-01-14T21:56:33.318338",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz",
    "gpus": {
      "driver_version": "415.25",
      "gpus": [
        {
          "model": "GeForce GTX TITAN X",
          "persistence_mode": false,
          "total_memory": 12209
        },
        {
          "model": "TITAN Xp",
          "persistence_mode": false,
          "total_memory": 12196
        }
      ]
    },
    "hostname": "octavia",
    "os": [
      "Linux",
      "Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic"
    ],
    "python_version": "3.6.7"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-01-14T21:56:31.967119",
  "status": "FAILED",
  "stop_time": "2019-01-14T21:56:33.403513"
}